export const SCHOLARSHIPS_DB = [
  {
    id: 1,
    name: 'National Scholarship Scheme (NSP)',
    provider: 'Ministry of Education',
    amount: 100000,
    eligibility: 'Students from low-income families',
    category: 'Financial Aid',
    deadline: '2026-08-31',
    website: 'https://scholarships.gov.in',
    description: 'Full tuition fee support for deserving students',
  },
  {
    id: 2,
    name: 'AICTE Career Advancement Scholarship',
    provider: 'AICTE',
    amount: 150000,
    eligibility: 'Engineering students with 75%+ marks',
    category: 'Merit-Based',
    deadline: '2026-07-31',
    website: 'https://aicte.gov.in',
    description: 'Merit-based scholarship for top engineering students',
  },
  {
    id: 3,
    name: 'DST Women Scientist Scholarship',
    provider: 'Department of Science & Technology',
    amount: 200000,
    eligibility: 'Female students in science streams',
    category: 'Women Empowerment',
    deadline: '2026-09-15',
    website: 'https://dst.gov.in',
    description: 'Special scholarship for women pursuing science',
  },
  {
    id: 4,
    name: 'Infosys Foundation Scholarship',
    provider: 'Infosys',
    amount: 250000,
    eligibility: 'First-generation students with 80%+ marks',
    category: 'Corporate',
    deadline: '2026-08-15',
    website: 'https://infosys.com/foundation',
    description: 'Corporate scholarship for deserving students',
  },
  {
    id: 5,
    name: 'TCS Scholar Program',
    provider: 'Tata Consultancy Services',
    amount: 300000,
    eligibility: 'IT/CS students with 85%+ marks',
    category: 'Corporate',
    deadline: '2026-09-30',
    website: 'https://tcs.com/careers',
    description: 'TCS scholarship for IT specialists',
  },
  {
    id: 6,
    name: 'State Merit Scholarship',
    provider: 'Tamil Nadu Government',
    amount: 75000,
    eligibility: 'State board students with 90%+ marks',
    category: 'State Government',
    deadline: '2026-07-15',
    website: 'https://tnscholarships.gov.in',
    description: 'Merit scholarship from state government',
  },
  {
    id: 7,
    name: 'HDFC Bank Education Loan Scholarship',
    provider: 'HDFC Bank',
    amount: 500000,
    eligibility: 'Students availing education loan',
    category: 'Loan Support',
    deadline: '2026-12-31',
    website: 'https://hdfcbank.com',
    description: 'Partial waiver on education loan interest',
  },
  {
    id: 8,
    name: 'Google Scholarship for Women Technologists',
    provider: 'Google',
    amount: 350000,
    eligibility: 'Female engineering students',
    category: 'Tech Company',
    deadline: '2026-10-31',
    website: 'https://google.com/scholarships',
    description: 'Google Women Technologists scholarship',
  },
];
